### ISSUE TITLE
[Bug] Settings do not work in conjunction with each other

### ISSUE THREAD

**Issue by Gitoffthelawn** [Frozen-Developers/android-cache-cleaner#18]
Enabling both 'Clean on app startup' and 'Exit after clean up' will result in the latter setting being ignored.

**Comment by Kuci** [comment]
Actually, this is not a bug. Description of 'Exit after clean up' setting states: 'Exit after *Clean* button is clicked and clean up is completed'. Therefore, you have to perform manual clean up if you want it to exit automatically. Otherwise, using both settings at once may prevent the user from accessing the UI.

**Comment by Gitoffthelawn** [comment]
"Otherwise, using both settings at once may prevent the user from accessing the UI."  Lol... that's what I was kind of hoping to do!  ;)

Of course it makes it near impossible to change the settings again... but clearing the Cache Cleaner app's data would take care of that!

**Comment by Kuci** [comment]
I am afraid that the vast majority of users would not be able to do that and would rather call the app useless.

**Comment by Gitoffthelawn** [comment]
I concur!
