### ISSUE TITLE
GitHub is not ethical

### ISSUE THREAD

**Issue by RyDroid** [Frozen-Developers/android-cache-cleaner#28]
Hi.
I think that it would be better if the repo is more ethicaly hosted. https://www.gnu.org/software/repo-criteria.html
Regards.

**Comment by Kuci** [comment]
Hello @RyDroid, TL;DR. What is your point ?

**Comment by RyDroid** [comment]
GitHub is based on [proprietary software](https://www.gnu.org/philosophy/proprietary.html), sends [proprietary JavaScript](https://www.gnu.org/philosophy/javascript-trap.html) and can not be self-hosted. So I think that it would be better to use a more ethical repo software platform (like GitLab Community Edition, Gogs or GitBucket).

**Comment by Kuci** [comment]
We have been using GitHub not only because the fact it is the biggest player in the game, providing superior performance and features, but because we want to keep our projects as close to the community as possible too.
And when it comes to the fact that it is a proprietary software and can not be self-hosted... Well, it means literally nothing to us. If it was open source and could be self-hosted, it would change nothing.

**Comment by RyDroid** [comment]
If it was free/libre and self-hostable, we could use it to do a more decentralized Internet and easily switch if one day we consider that GitHub does at least one bad thing (for me proprietary JavaScript is already a bad thing) (remember what happened to Google Code and SourceForge).

**Comment by Kuci** [comment]
We can push our code to another remote without any hassle, whenever we want and we sure will do so if GitHub will ever not be able to satisfy our needs. For now, I don't see any reason for migration.
