### ISSUE TITLE
Android 6.0 issue and quick solution

### ISSUE THREAD

**Issue by KashifAnwaar** [Frozen-Developers/android-cache-cleaner#37]
It says cache cleaned in android 6.0 devices, that sounds fake when user check again. at-least you should say it won't work.

Best and easy solution is there - take user to Settings-> Storage -> Cached data 
where all cache can be cleaned in one click by user.

**Comment by Kuci** [comment]
Hi @KashifAnwaar, thanks for writing. Actually, external cache IS being cleaned. But thanks to your point about Settings, we do not need this app anymore.

**Comment by kawadkarrocky** [comment]
Hi, Lubo as it seemingly we have wide range of android devices for Marshmallow, so it is not a good option that we are using to open intent for opening action to internal storage as many of the devices do not directly open  the cache data of internal system storage, hence we need to practice a better method to do so rather than to open the default system setting. any suggestion would be appreciated.
