### ISSUE TITLE
Easy accessible button to start Android's new cache manager

### ISSUE THREAD

**Issue by gsantner** [Frozen-Developers/android-cache-cleaner#50]
Please add a simple option/button to the app if the android version is >= API 25. I looked a little a little into it, and all that needs to be done is starting an intent with the following action to show up the delete-cache-UI: `android.os.storage.action.MANAGE_STORAGE`. This was added at API level 25.

Try it:
`adb shell am start -a "android.os.storage.action.MANAGE_STORAGE"`

```
if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.N_MR1) {
    startActivity(new Intent(StorageManager.ACTION_MANAGE_STORAGE));
}
```

Source: <https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/os/storage/StorageManager.java#112>

**Comment by lubo** [comment]
Hi @gsantner, thank you for writing. Unfortunately, I'm having trouble understanding the purpose of your suggestion. I've tried using storage manager, but it has nothing to do with cache cleaning. Could you provide more info, please?

**Comment by gsantner** [comment]
This intent starts up the new activity (>= API level 25) where cache can be cleaned. Exactly what is described in the README: `Settings -> Storage & USB-> Internal storage and click on Cached data`.  Would make it easier to have this just one click away, than having to look somewhere deep in the settings.

**Comment by lubo** [comment]
Actually, that is not right. I'm using AOSP 7.1.2 and it opened a screen, on which I was able to delete my Downloads and to remove apps I've not used for a long time. No cache mentioned and no cache cleaned after using it.

**Comment by gsantner** [comment]
Ups, sorry this was just the delete "old stuff" activity, right (which I also thought would  be a good idea to add). The one with the cache UI is `.Settings$StorageSettingsActivity`.

```
if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.M) {
     Intent intent = new Intent();
     intent.setComponent(new ComponentName("com.android.settings", "com.android.settings.Settings$StorageSettingsActivity"));
     startActivity(intent);
}
```

**Comment by lubo** [comment]
Well, this seems to be a little bit out of concept for this app. If you're on Marshmallow or newer, your device has most likely so much storage you don't even need cache cleaning at all (and you probably shouldn't clean it if not necessary). Cleaning it would probably degrade apps performance for little or no benefit on the new devices. Therefore, I'm not really interested in providing a shortcut to settings, which could negatively influence apps performance of those users, who just want to see higher numbers without really knowing what is going on. This app was meant for those of us, who had very little storage (I had less than 1 GiB  on Sony Xperia Neo V with Android 4 and newer) and cleaning cache would make a difference even when applying app updates. Since this era seems to be finally over, I'm not interested in putting so much effort into this app anymore.

**Comment by gsantner** [comment]
Okay.

Just one thing (not related to the app):

> you're on Marshmallow or newer, your device has most likely so much storage you don't even need cache cleaning at all

Not at all, there are still a lot of 8GB devices out there (and new released). On many roms the Adoptable-Storage feature is deactivated, or theres simply no sd slot.

**Comment by lubo** [comment]
Still, having a 3rd party app was the only option back then. Now, we have it in Settings and since you should not use it that often, I don't find it necessary to have a shortcut for that. Also, downloading this whole app just for the shortcut makes no sense.
