### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [Frozen-Developers/android-cache-cleaner#52]
Hi @Frozen-Developers

I found [this app](https://play.google.com/store/apps/details?id=com.ikramshah.cache.cleaner) on the Google Play Store. This guy just took the source code and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under MIT license and this guy is violating it;
* He is falsely claiming he made the app;

**Comment by lubo** [comment]
Hello @Poussinou, sorry for the late reply. We're aware that there're many false copies of our software and we're not planning on taking any actions. At the time of making the sources publicly available, we knew that it will happen one day and since we have not been hurt in any way, we simply do not care. The only people that are being hurt are the users and it's their responsibility to only use software by the legitimate developers.

Thank you for your initiative, though. If you want to help the community, you can still report those people on your own.

**Comment by Poussinou** [comment]
Thanks for your answer, I understand your position

I'll do

**Comment by Poussinou** [comment]
@Lubo The app is down. Did you receive any mail about this?

**Comment by lubo** [comment]
I did not, but it's probably our internal issue. I see the app down, though.
